### DISCUSSION TITLE
Allowing aliases in the YAML configuration

### DISCUSSION THREAD

**Discussion by DannyBen** [rubocop/rubocop#11207] [Ideas]
With the questionable changes in Psych 4 to `safe_load`, the simplest YAML notion of anchors is not enabled by default.

Would it make sense for Rubocop to allow YAML aliaeses?

I would like to avoid repeating myself in the rubocop configuration, if possible.

The below fails, and can be made to work with `aliases: true` in the YAML loading function:

```yaml
# The `ConfigValidator` class is a DSL, let it be
Metrics/AbcSize: &validator
  Exclude:
    - lib/bashly/config_validator.rb

Metrics/CyclomaticComplexity: *validator
Metrics/PerceivedComplexity: *validator
Metrics/MethodLength: *validator
Style/GuardClause: *validator
```
