### DISCUSSION TITLE
How to properly format deeply nested hashes?

### DISCUSSION THREAD

**Discussion by basicfeatures** [rubocop/rubocop#12167] [Q&A]
Hi,

I have these camera emulations in the form of Ruby hashes ([canon_eos_1d_mark_ii_fuji_160c_2c.dcp.zip](https://github.com/rubocop/rubocop/files/12468841/canon_eos_1d_mark_ii_fuji_160c_2c.dcp.zip)):

Unfortunately my Rubocop formats them like:
```
{ "dcpData" => { "ProfileName" => "Fuji 160C 2C", "CalibrationIlluminant1" => "17", "CalibrationIlluminant2" => "21",
                 "ColorMatrix1" => { "2,2" => "0.853700", "2,1" => "0.132800", "2,0" => "-0.097800", "1,2" => "0.297700", "1,1" => "1.409500", "1,0" => "-0.679400", "0,2" => "-0.024600", "0,1" => "-0.162300", "0,0" => "0.718000" }, "ColorMatrix2" => { "2,2" => "0.866400", "2,1" => "0.191900", "2,0" => "-0.174400", "1,2" => "0.250400", "1,1" => "1.594800", "1,0" => "-0.831200", "0,2" => "-0.072400", "0,1" => "-0.058200", "0,0" => "0.626400" }, "ForwardMatrix1"
```

How do I instead make it like:
```
{
  "dcpData" => {
    "ProfileName" => "Fuji 160C 2C", "CalibrationIlluminant1" => "17", "CalibrationIlluminant2" => "21",
    "ColorMatrix1" => {
      "2,2" => "0.853700", "2,1" => "0.132800", "2,0" => "-0.097800", "1,2" => "0.297700", "1,1" => "1.409500", "1,0" => "-0.679400", "0,2" => "-0.024600", "0,1" => "-0.162300", "0,0" => "0.718000"
    }, "ColorMatrix2" => {
      "2,2" => "0.866400", "2,1" => "0.191900", "2,0" => "-0.174400", "1,2" => "0.250400", "1,1" => "1.594800", "1,0" => "-0.831200", "0,2" => "-0.072400", "0,1" => "-0.058200", "0,0" => "0.626400"
    }, "ForwardMatrix1" ...
```
`~/.rubocop.yml`
```yml
# Use double quotes for string literals
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Use space inside string interpolation
Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

# Use consistent indentation for the first argument
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

# Use fixed indentation for argument alignment
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

# Use fixed indentation for hash alignment
Layout/HashAlignment:
  EnforcedStyle: with_fixed_indentation

# Use consistent indentation for the first hash element
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# Disable the FrozenStringLiteralComment cop
Style/FrozenStringLiteralComment:
  Enabled: false

# Enforce line length limit
Metrics/LineLength:
  Max: 100  # or whatever maximum length you prefer

# Enforce block-style hash layout
Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line

# Enforce consistent comma style in multiline collections
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
```

Cheers, thanks a lot guys!
