### DISCUSSION TITLE
Troubleshooting: "Why `rubocop` autofixes _this way_"?

### DISCUSSION THREAD

**Discussion by stdedos** [rubocop/rubocop#13315] [Q&A]
In the interest of avoiding opening N issues (discussions, whatever), I'll use this "mega-thread" to ask "why is this fixed like _that_, when I expected _this_?"

Maybe it will serve as "partially" un-off FAQ for beginners (or maybe it will get integrated somewhere)

My config, unless specified, is:

```yaml
require:
  - rubocop-performance

AllCops:
  ActiveSupportExtensionsEnabled: true
  NewCops: enable
  Exclude:
    - 'b/c/**/*'

# Disabling because of build issues. See:
# * https://github.com/rubocop/rubocop/discussions/13294
# * https://github.com/rubocop/rubocop/issues/13299
# * https://github.com/rubocop/rubocop/issues/13302
Style/BlockDelimiters:
  Enabled: false

# Minimize git-diff changes, by trying to mimic black:
# https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#how-black-wraps-lines
Layout/MultilineArrayBraceLayout:
  EnforcedStyle: symmetrical

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/FirstHashElementLineBreak:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
```

and

```console
$ bin/bundle exec rubocop -V
1.66.1 (using Parser 3.3.5.0, rubocop-ast 1.32.3, running on jruby 3.1.4) [java]
  - rubocop-performance 1.22.1
```

**Comment by stdedos** [comment]
```patch
diff --git a/xxxxxx/xxxxxxx/xxx/test/xxx/xxxx/xxxxxx_server_spec.rb b/xxxxxx/xxxxxxx/xxx/test/xxx/xxxx/xxxxxx_server_spec.rb
index 17210a0914a..1283d6bea36 100644
--- a/xxxxxx/xxxxxxx/xxx/test/xxx/xxxx/xxxxxx_server_spec.rb
+++ b/xxxxxx/xxxxxxx/xxx/test/xxx/xxxx/xxxxxx_server_spec.rb
@@ -78,6 +76,7 @@
     end
 
     shared_examples 'file is found' do
       let(:asset) { 'xxxxxx-xxxxxx-xxxxx-xxxxx-xxxxx.json' }
-      let(:body) { Resources.to_string(Resources.get_resource("#{@xxxxxxxx_xxxxxx_xxxxxxx_path}/#{asset}"), java.nio.charset.StandardCharsets::UTF_8) }
+      let(:body) {
+ Resources.to_string(Resources.get_resource("#{@xxxxxxxx_xxxxxx_xxxxxxx_path}/#{asset}"), java.nio.charset.StandardCharsets::UTF_8) }
```

While, yes, "it does reduce the line-size", I don't think it fits "any" correct indentation formula

(pls don't offer me to "relax test config" :pray: ik I can do that. I also know that people read >100ch lines harder)

**Reply by stdedos** [reply]
"in the same spirit"

```patch
diff --git a/xxxxxx/xxxxxxx/xxx/test/xxx/xxxx/xxxxxx_server_spec.rb b/xxxxxx/xxxxxxx/xxx/test/xxx/xxxx/xxxxxx_server_spec.rb
index 17210a0914a..1283d6bea36 100644
--- a/xxxxxx/xxxxxxx/xxx/test/xxx/xxxx/xxxxxx_server_spec.rb
+++ b/xxxxxx/xxxxxxx/xxx/test/xxx/xxxx/xxxxxx_server_spec.rb
@@ -83,6 +82,7 @@
 
-      it_behaves_like 'a file is served', cache_control: false, has_csp: true, content_type: 'application/json; charset=utf-8'
+      it_behaves_like 'a file is served', cache_control: false, has_csp: true, 
+content_type: 'application/json; charset=utf-8'
 
       context 'under /assets' do
         let(:asset) { "assets/xxxxxx-xxxxxx-xxxxx-xxxxx-xxxxx.json" }

```

Although this "sort of" makes sense. But why not honor

```yaml
Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument
```
?

(and/or hopefully an end result of

```ruby
      it_behaves_like(
        'a file is served',
        cache_control: false,
        has_csp: true,
        content_type: 'application/json; charset=utf-8',
      )
```
?)

**Reply by stdedos** [reply]
Also similarly

```patch
diff --git a/xxxxxx/xxxxxxx/xxx/test/xxx/xxxx/xxxxxx_server_spec.rb b/xxxxxx/xxxxxxx/xxx/test/xxx/xxxx/xxxxxx_server_spec.rb
index 17210a0914a..1283d6bea36 100644
--- a/xxxxxx/xxxxxxx/xxx/test/xxx/xxxx/xxxxxx_server_spec.rb
+++ b/xxxxxx/xxxxxxx/xxx/test/xxx/xxxx/xxxxxx_server_spec.rb
@@ -217,9 +231,10 @@ describe 'xx.xxxxx.processor9.xxxxxxx.xxxxxxx.xxxxxxx.XXXXXXServer' do
 
     context 'multi-part upload' do
       subject do
-        HTTParty.post("http://localhost:#{port}/api/do", body: { a_val: '42', a_file: csv_file }, multipart: true, timeout: 5)
+        HTTParty.post("http://localhost:#{port}/api/do", body: { a_val: '42', a_file: csv_file }, multipart: true, 
+timeout: 5)
       end
 
       let(:csv_file) { File.open(temp_csv_file) } # use a regular File due HTTParty
       let(:temp_csv_file) do
         file = Tempfile.new('xxxxxx-server-test')
```

All of those are `C: [Corrected] Layout/LineLength: Line is too long. [126/120]` issues - but they seem to not recursively trigger other cops to re-process the edit results (or however that works in rubocop)

**Reply by stdedos** [reply]
And a "clear violation" of what I am trying:

```ruby
require 'spec/spec_helper'

describe SomeClass do
  ...
  context "performing some action", :slow => true do
    ...
    def perform_action(number = 11_000, start_from = 0)
      require "benchmark"

      perform_task do
        ...
        (1..number).each do |i|
          ...
          ttable.insert({ "xxxxxxxxxxxxxxxxxxx" => xxxx, "xxxx" => "XXXX", 
"xxxx" => ld((Date.current - (xxx/xxx).days).strftime("xxxx-xx-xx")).get_local_millis, "xxxxxxxxxxxxx" => xxx.to_f })
```

Naturally, the rspec is _much larger_ - but I cannot post it.
Fixing this (**unexecutable**) ruby code in isolation is okay-ish (instead of chopping down, it just chops at line-length limit)

**Reply by stdedos** [reply]
I guess the theme of this thread is: Why do I get `Layout/LineLength` "autofixes" which hang the next line at 0-char or 1-char, instead of "beautifying" the code? (and the style I am going with is "chop always on multiline")

**Comment by stdedos** [comment]
I am trying to reformat

```ruby
require 'spec/spec_helper'

describe XxxxxXxxxx do
  before { stub_const('UTF8_MARKER', XxxxxXxxxx::Xxxxxxxxxxxx::UTF8_MARKER.to_java(:char)) }

  before(:all) do
    @user = integration_login
    @user.language = 'xx_XX'
    @user.save

    @default_options = { :decimal_separator => ",", :show_metadata => false }
    @default_csv_options = { :row_sep => "\n" }
  end

  after(:all) do
    @user = integration_login
    @user.language = 'xx_XX'
    @user.save
  end

  def insert_test_data
    @p1 = FactoryBot.create(:xxxxxxx, :code => "AAA", :name => "AAA", :name_xx => 'XXXxxxx XXX', :is_xxxxxxx => "yes")
    @p2 = FactoryBot.create(:xxxxxxx, :code => "BBB", :name => "BBB", :is_xxxxxxx => "yes")
    @l1 = FactoryBot.create(:xxxxxxxx, :code => 'ccc', :name => 'ccc', :xxxxxx_xxxxxx => 3)
    @l2 = FactoryBot.create(:xxxxxxxx, :code => 'ddd', :name => 'ddd')

    @pl11 = FactoryBot.create(:xxxxxxx_xxxxxxxx, :xxxxxxx => @p1, :xxxxxxxx => @l1, :xxxxxx_xxxxxxxxxx => d('2012-04-01'), :xxxxxx_xxxxxxx => 1.0, :xxxxxxx_xxxxxxxx => true, :xxxxxxxxxx_xxxx => Xxxxxxxxxxxxxxx::Xxxxxxxxx::XXXXXXXXXX, :xxxxxxx_xxxxx => 123, :xxxxxxx_xxxxx => nil)
    @pl21 = FactoryBot.create(:xxxxxxxx_xxxxxxx, :xxxxxxx => @p2, :xxxxxxxx => @l1, :xxxxxx_xxxxxxxxxx => d('2011-04-01'), :xxxxxx_xxxxxxx => 2.0, :xxxxxxx_xxxxxxxx => false, :xxxxxxxxxxxxxxx => 234)
    @pl12 = FactoryBot.create(:xxxxxxx_xxxxxxxx, :xxxxxxx => @p1, :xxxxxxxx => @l2, :xxxxxx_xxxxxxxxxx => d('2012-12-01'), :xxxxxx_xxxxxxx => 12.0)
    @pl22 = FactoryBot.create(:xxxxxxxx_xxxxxxx, :xxxxxxx => @p2, :xxxxxxxx => @l2, :xxxxxx_xxxxxxxxxx => d('2012-12-12'), :xxxxxx_xxxxxxx => 22.0123456789, :xxxxxxxxxxx => Xxxxxxxxxxxxxxx::Xxxxxxxxxx::XX_XXXX, :xxxxxxx_xxxxxxxx => false)

    FactoryBot.create(:xxxxxxxxxxx, :xxxxxxx_xxxxxxxx => @pl11, :date => Xxxxxxx::Xxxxxxxxx.current, :xxxxxx_xxxxxxx => 1.0)
    FactoryBot.create(:xxxxxxxxxxx, :xxxxxxx_xxxxxxxx => @pl12, :date => Xxxxxxx::Xxxxxxxxx.current, :xxxxxx_xxxxxxx => 2.0)

    FactoryBot.create(:xxxxxxxxxxxxxxx, :xxxxxxx_xxxxxxxx => @pl11, :date => Xxxxxxx::Xxxxxxxxx.current, :xxxxxx_xxxxxxx => 1.0)
  end

  # 2706 more lines here ....
end
```

file. I have improved my config (from above) as

```yaml
require:
  - rubocop-performance
  # https://github.com/rubocop/rubocop/discussions/13306
  # - rubocop-rails

AllCops:
  ActiveSupportExtensionsEnabled: true
  NewCops: enable
  Exclude:
    - 'b/c/**/*'

# Disabling because of build issues. See:
# * https://github.com/rubocop/rubocop/discussions/13294
# * https://github.com/rubocop/rubocop/issues/13299
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

# Minimize git-diff changes, by trying to mimic black:
# https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#how-black-wraps-lines
Layout/MultilineArrayBraceLayout:
  EnforcedStyle: symmetrical

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
```

If I re-format the fragment above, I get (the expected)

```ruby
require 'spec/spec_helper'

describe XxxxxXxxxx do
  before { stub_const('UTF8_MARKER', XxxxxXxxxx::Xxxxxxxxxxxx::UTF8_MARKER.to_java(:char)) }

  before(:all) do
    @user = integration_login
    @user.language = 'xx_XX'
    @user.save

    @default_options = { decimal_separator: ',', show_metadata: false }
    @default_csv_options = { row_sep: "\n" }
  end

  after(:all) do
    @user = integration_login
    @user.language = 'xx_XX'
    @user.save
  end

  def insert_test_data
    @p1 = FactoryBot.create(:xxxxxxx, code: 'AAA', name: 'AAA', name_xx: 'XXXxxxx XXX', is_xxxxxxx: 'yes')
    @p2 = FactoryBot.create(:xxxxxxx, code: 'BBB', name: 'BBB', is_xxxxxxx: 'yes')
    @l1 = FactoryBot.create(:xxxxxxxx, code: 'ccc', name: 'ccc', xxxxxx_xxxxxx: 3)
    @l2 = FactoryBot.create(:xxxxxxxx, code: 'ddd', name: 'ddd')

    @pl11 = FactoryBot.create(
      :xxxxxxx_xxxxxxxx,
      xxxxxxx: @p1,
      xxxxxxxx: @l1,
      xxxxxx_xxxxxxxxxx: d('2012-04-01'),
      xxxxxx_xxxxxxx: 1.0,
      xxxxxxx_xxxxxxxx: true,
      xxxxxxxxxx_xxxx: Xxxxxxxxxxxxxxx::Xxxxxxxxx::XXXXXXXXXX,
      xxxxxxx_xxxxx: 123,
      xxxxxxx_xxxxx: nil,
    )
    @pl21 = FactoryBot.create(
      :xxxxxxxx_xxxxxxx,
      xxxxxxx: @p2,
      xxxxxxxx: @l1,
      xxxxxx_xxxxxxxxxx: d('2011-04-01'),
      xxxxxx_xxxxxxx: 2.0,
      xxxxxxx_xxxxxxxx: false,
      xxxxxxxxxxxxxxx: 234,
    )
    @pl12 = FactoryBot.create(
      :xxxxxxx_xxxxxxxx,
      xxxxxxx: @p1,
      xxxxxxxx: @l2,
      xxxxxx_xxxxxxxxxx: d('2012-12-01'),
      xxxxxx_xxxxxxx: 12.0,
    )
    @pl22 = FactoryBot.create(
      :xxxxxxxx_xxxxxxx,
      xxxxxxx: @p2,
      xxxxxxxx: @l2,
      xxxxxx_xxxxxxxxxx: d('2012-12-12'),
      xxxxxx_xxxxxxx: 22.0123456789,
      xxxxxxxxxxx: Xxxxxxxxxxxxxxx::Xxxxxxxxxx::XX_XXXX,
      xxxxxxx_xxxxxxxx: false,
    )

    FactoryBot.create(
      :xxxxxxxxxxx,
      xxxxxxx_xxxxxxxx: @pl11,
      date: Xxxxxxx::Xxxxxxxxx.current,
      xxxxxx_xxxxxxx: 1.0,
    )
    FactoryBot.create(
      :xxxxxxxxxxx,
      xxxxxxx_xxxxxxxx: @pl12,
      date: Xxxxxxx::Xxxxxxxxx.current,
      xxxxxx_xxxxxxx: 2.0,
    )

    FactoryBot.create(
      :xxxxxxxxxxxxxxx,
      xxxxxxx_xxxxxxxx: @pl11,
      date: Xxxxxxx::Xxxxxxxxx.current,
      xxxxxx_xxxxxxx: 1.0,
    )
  end

  # 2706-formatted more lines here ....
end
```

However, when I reformat the ENTIRE file, I get

```ruby
require 'spec/spec_helper'

describe XxxxxXxxxx do
  before { stub_const('UTF8_MARKER', XxxxxXxxxx::Xxxxxxxxxxxx::UTF8_MARKER.to_java(:char)) }

  before(:all) do
    @user = integration_login
    @user.language = 'xx_XX'
    @user.save

    @default_options = { :decimal_separator => ",", :show_metadata => false }
    @default_csv_options = { :row_sep => "\n" }
  end

  after(:all) do
    @user = integration_login
    @user.language = 'xx_XX'
    @user.save
  end

  def insert_test_data
    @p1 = FactoryBot.create(:xxxxxxx, :code => "AAA", :name => "AAA", :name_xx => 'XXXxxxx XXX', :is_xxxxxxx => "yes")
    @p2 = FactoryBot.create(:xxxxxxx, :code => "BBB", :name => "BBB", :is_xxxxxxx => "yes")
    @l1 = FactoryBot.create(:xxxxxxxx, :code => 'ccc', :name => 'ccc', :xxxxxx_xxxxxx => 3)
    @l2 = FactoryBot.create(:xxxxxxxx, :code => 'ddd', :name => 'ddd')

    @pl11 = FactoryBot.create(:xxxxxxx_xxxxxxxx, :xxxxxxx => @p1, :xxxxxxxx => @l1,
:xxxxxx_xxxxxxxxxx => d('2012-04-01'), :xxxxxx_xxxxxxx => 1.0, :xxxxxxx_xxxxxxxx => true, :xxxxxxxxxx_xxxx => Xxxxxxxxxxxxxxx::Xxxxxxxxx::XXXXXXXXXX, :xxxxxxx_xxxxx => 123, :xxxxxxx_xxxxx => nil)
    @pl21 = FactoryBot.create(:xxxxxxxx_xxxxxxx, :xxxxxxx => @p2, :xxxxxxxx => @l1, 
:xxxxxx_xxxxxxxxxx => d('2011-04-01'), :xxxxxx_xxxxxxx => 2.0, :xxxxxxx_xxxxxxxx => false, :xxxxxxxxxxxxxxx => 234)
    @pl12 = FactoryBot.create(:xxxxxxx_xxxxxxxx, :xxxxxxx => @p1, :xxxxxxxx => @l2,
:xxxxxx_xxxxxxxxxx => d('2012-12-01'), :xxxxxx_xxxxxxx => 12.0)
    @pl22 = FactoryBot.create(:xxxxxxxx_xxxxxxx, :xxxxxxx => @p2, :xxxxxxxx => @l2,
:xxxxxx_xxxxxxxxxx => d('2012-12-12'), :xxxxxx_xxxxxxx => 22.0123456789, :xxxxxxxxxxx => Xxxxxxxxxxxxxxx::Xxxxxxxxxx::XX_XXXX, :xxxxxxx_xxxxxxxx => false)

    FactoryBot.create(:xxxxxxxxxxx, :xxxxxxx_xxxxxxxx => @pl11, :date => Xxxxxxx::Xxxxxxxxx.current,
:xxxxxx_xxxxxxx => 1.0)
    FactoryBot.create(:xxxxxxxxxxx, :xxxxxxx_xxxxxxxx => @pl12, :date => Xxxxxxx::Xxxxxxxxx.current,
:xxxxxx_xxxxxxx => 2.0)

    FactoryBot.create(:xxxxxxxxxxxxxxx, :xxxxxxx_xxxxxxxx => @pl11, :date => Xxxxxxx::Xxxxxxxxx.current,
:xxxxxx_xxxxxxx => 1.0)
  end

  ...
```

I cannot comprehend why is this happening. Naturally, I cannot disclose 3k lines of code.
(OTOH, why anything formatted in this function would have to do with the rest of the code ...)

Rubocop can take the above (as a snippet, NOT the whole file) and end-up in the same expected format.
However, I would like to understand what could possibly be the issue that blocks Rubocop from doing what I expect it to do.

**Comment by stdedos** [comment]
Same config as above:

```yaml
require:
  - rubocop-performance
  # https://github.com/rubocop/rubocop/discussions/13306
  # - rubocop-rails

AllCops:
  ActiveSupportExtensionsEnabled: true
  NewCops: enable
  Exclude:
    - 'b/c/**/*'

# Disabling because of build issues. See:
# * https://github.com/rubocop/rubocop/discussions/13294
# * https://github.com/rubocop/rubocop/issues/13299
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

# Minimize git-diff changes, by trying to mimic black:
# https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#how-black-wraps-lines
Layout/MultilineArrayBraceLayout:
  EnforcedStyle: symmetrical

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
```

Why reformat

```ruby
class XxxxxxxXxx < Xxxxxxx::XxxxXxx
  def xxxxxx_xxx(xxxxxxxx_xxxxxxxxx, xxxxxx_xx, xxxxxxxxxx = nil, yyyyy_yyyyyyyyyy_yyy_yyyyyyyyyy = nil)
    xxx_xxxxxxx = {
      xxx_xxxxxxx: { xxxxxxxx_xxx: xx, xxxxxxxxxxxx: xxxxxxxxxxxx&.xx, xxxxxxxxxxx_xx_xxxxxxxxx: !xxxxxxxxx_xxxxxxxxx },
    }
    if yyyyy_yyyyyyyyyy_yyy_yyyyyyyyyy
      xxx_xxxxxxx[:xxx_xxxxxxx] = xxx_xxxxxxx[:xxx_xxxxxxx].merge(yyyyy_yyyyyyyyyy_yyy_yyyyyyyyyy: yyyyy_yyyyyyyyyy_yyy_yyyyyyyyyy)
    end
  end
end
```

as

```ruby
class XxxxxxxXxx < Xxxxxxx::XxxxXxx
  def xxxxxx_xxx(_xxxxxxxx_xxxxxxxxx, _xxxxxx_xx, _xxxxxxxxxx = nil, yyyyy_yyyyyyyyyy_yyy_yyyyyyyyyy = nil)
    xxx_xxxxxxx = {
      xxx_xxxxxxx: { xxxxxxxx_xxx: xx, xxxxxxxxxxxx: xxxxxxxxxxxx&.xx, xxxxxxxxxxx_xx_xxxxxxxxx: !xxxxxxxxx_xxxxxxxxx },
    }
    return unless yyyyy_yyyyyyyyyy_yyy_yyyyyyyyyy

    xxx_xxxxxxx[:xxx_xxxxxxx] =
      xxx_xxxxxxx[:xxx_xxxxxxx].merge(yyyyy_yyyyyyyyyy_yyy_yyyyyyyyyy: yyyyy_yyyyyyyyyy_yyy_yyyyyyyyyy)
  end
end
```

?

Isn't it more beautiful to split on the function call instead?

```ruby
      xxx_xxxxxxx[:xxx_xxxxxxx] = xxx_xxxxxxx[:xxx_xxxxxxx].merge(
        yyyyy_yyyyyyyyyy_yyy_yyyyyyyyyy: yyyyy_yyyyyyyyyy_yyy_yyyyyyyyyy
      )
```

Especially given that the sheer width of the (single) kwarg.

**Reply by stdedos** [reply]
In the same neighborhood, I guess:

```ruby
def xx_xxxx_xxxxx_xxxxxxx_xx_xxxxxxxxx_xxxxxx(_yyy, _zzz)
  xxxxxx =
    {
      'xxxxx_xxxxxxxxx' => '',
      'xxx_xxxxxxxxx' => 'xxxxx_xxxxxxxxx',
      'xxxxxx_xx' => 'xxxxxxx',
      'xxxxxxx_xxxxx_xxxxx_xxx' => true,
      'xxxxxx_xxxxxxxxx' => [
        {
          'xxxxxxxx' => '=',
          'xxxxxx' => 'xxxxx::xxxxx_xxxxxxxxx:xxxx_xx_xxxxxxxxx_xxxxxx',
          'xxxxx' => 'xxxx',
          'xxxx_xxxx' => 'xxx',
        },
        {
          'xxxxxxxx' => '>',
          'xxxxxx' => 'xxxxx::xxxxx_xxxxxxxxx:xxxxxxxx_xxxx',
          'xxxxx' => '0',
          'xxxx_xxxx' => 'xxx',
        },
        {
          'xxxxxxxx' => '!=',
          'xxxxxx' => 'xxxxx::xxxxx_xxxxxxxxx:xxxx_xx',
          'xxxxx' => '[xxxx]',
          'xxxx_xxxx' => 'xxx',
        },
      ],
      'xxxxxx_xxxxxx' => [
        { 'xxxxxx' => 'xxxxx::xxxxxxx:xxxx' },
        { 'xxxxxx' => 'xxxxx::xxxxxxxx:xxxx' },
        { 'xxxxxx' => 'xxxxx::xxxxx_xxxxxxxxx:xxxxxxxx_xxxxxxxxx' },
        { 'xxxxxx' => 'xxxxx::xxxxx_xxxxxxxxx:xxxxxxxx_xxxx' },
      ],
    }

  puts xxxxxx
  xxxxxx
end
```

to become

```ruby
def xx_xxxx_xxxxx_xxxxxxx_xx_xxxxxxxxx_xxxxxx(_yyy, _zzz)
  xxxxxx = {
    'xxxxx_xxxxxxxxx' => '',
    'xxx_xxxxxxxxx' => 'xxxxx_xxxxxxxxx',
    'xxxxxx_xx' => 'xxxxxxx',
    'xxxxxxx_xxxxx_xxxxx_xxx' => true,
    'xxxxxx_xxxxxxxxx' => [
      {
        'xxxxxxxx' => '=',
        'xxxxxx' => 'xxxxx::xxxxx_xxxxxxxxx:xxxx_xx_xxxxxxxxx_xxxxxx',
        'xxxxx' => 'xxxx',
        'xxxx_xxxx' => 'xxx',
      },
      {
        'xxxxxxxx' => '>',
        'xxxxxx' => 'xxxxx::xxxxx_xxxxxxxxx:xxxxxxxx_xxxx',
        'xxxxx' => '0',
        'xxxx_xxxx' => 'xxx',
      },
      {
        'xxxxxxxx' => '!=',
        'xxxxxx' => 'xxxxx::xxxxx_xxxxxxxxx:xxxx_xx',
        'xxxxx' => '[xxxx]',
        'xxxx_xxxx' => 'xxx',
      },
    ],
    'xxxxxx_xxxxxx' => [
      { 'xxxxxx' => 'xxxxx::xxxxxxx:xxxx' },
      { 'xxxxxx' => 'xxxxx::xxxxxxxx:xxxx' },
      { 'xxxxxx' => 'xxxxx::xxxxx_xxxxxxxxx:xxxxxxxx_xxxxxxxxx' },
      { 'xxxxxx' => 'xxxxx::xxxxx_xxxxxxxxx:xxxxxxxx_xxxx' },
    ],
  }

  puts xxxxxx
  xxxxxx
end
```

instead?

**Comment by stdedos** [comment]
Same config as above:

```yaml
require:
  - rubocop-performance
  # https://github.com/rubocop/rubocop/discussions/13306
  # - rubocop-rails

AllCops:
  ActiveSupportExtensionsEnabled: true
  NewCops: enable
  Exclude:
    - 'b/c/**/*'

# Disabling because of build issues. See:
# * https://github.com/rubocop/rubocop/discussions/13294
# * https://github.com/rubocop/rubocop/issues/13299
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

# Minimize git-diff changes, by trying to mimic black:
# https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#how-black-wraps-lines
Layout/MultilineArrayBraceLayout:
  EnforcedStyle: symmetrical

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
```

Why reformat


```ruby
  def xxxxxx
    @xx_xx = @xx_xx.xxxxxx(
      Xxx.xxxxxxxxxxxxxx.xxxxxxx
        .xxxxxxxxxxxxxxxxxxxxxxxxx(@xxxxx_xxxxx_xxxxx)
        .xxxxx,
    )
    .xxxxxxxx
  end
``` 

as

```ruby
  def xxxxxx
    @xx_xx = @xx_xx.xxxxxx(
      Xxx.xxxxxxxxxxxxxx.xxxxxxx
        .xxxxxxxxxxxxxxxxxxxxxxxxx(@xxxxx_xxxxx_xxxxx)
        .xxxxx,
    )
               .xxxxxxxx
  end
``` 

?

Specifically, the

```
    )
               .xxxxxxxx
```

looks weird.

"More natural" would be `).xxxxxxxx` I guess (or as-original even)
