### DISCUSSION TITLE
Apply different styles to a handful of files

### DISCUSSION THREAD

**Discussion by stdedos** [rubocop/rubocop#13344] [Q&A] [answered]
Is it possible that a cop will continue use its default

```yaml
# e.g.
Style/AccessorGrouping:
  EnforcedStyle: grouped
```

but then for some files, I use a different style?

```yaml
# e.g.
Style/AccessorGrouping:
  EnforcedStyle: grouped
  Override:
    - 'path/to/file*.rb':
       EnforcedStyle: separate
    - 'other/file*.rb':
       Enabled: false
```

**Comment by dvandersluis** [comment, marked as answer]
It's not possible to specify different `EnforcedStyle`s for the same cop. 

Disabling for specific files is possible, using the `Include` or `Exclude` configuration (see https://docs.rubocop.org/rubocop/1.67/configuration.html#cop-specific-include-and-exclude)

```yaml
Style/AccessorGrouping:
  Exclude:
    - 'other/file*.rb'
```

**Reply by stdedos** [reply]
> It's not possible to specify different `EnforcedStyles` for the same cop.

I am thinking that "it is possible"- for example

```
/my_project
  ├── .rubocop.yml       
  ├── file1.rb
  └── /app               
      └── .rubocop.yml   
      └── file2.rb
```

`.rubocop.yml`

```yaml
Style/AccessorGrouping:
  EnforcedStyle: grouped
# which is the default rly - but just for demonstration
```

`app/.rubocop.yml`

```yaml
inherit_from: ../.rubocop.yml

Style/AccessorGrouping:
  EnforcedStyle: separate
```

... but then it would apply to a whole directory. Idk how problematic that is (anything goes for _now_, but may not be)
