### ISSUE TITLE
RedundantSelf cop causing syntax errors when on it's own with trailing .

### ISSUE THREAD

**Issue by KieranP** [rubocop/rubocop#10300]
## Config

```yaml
Layout/DotPosition:
  EnforcedStyle: trailing

Style/RedundantSelf:
  Enabled: true
```

## Original Code

```ruby
subs_by_user = self
  .where(user_id: user.id)
```

## Expected behavior

Self is not removed, because it isn't redundant once the trailing . is added:

```ruby
subs_by_user = self.
  where(user_id: user.id)
```

## Actual behavior

Trailing dot is added, then self is removed:

```ruby
subs_by_user = .
  where(user_id: user.id)
```

## RuboCop version

```
1.23.0 (using Parser 3.0.3.2, rubocop-ast 1.15.0, running on ruby 2.5.8 x86_64-darwin20)
  - rubocop-performance 1.12.0
  - rubocop-rails 2.12.4
```
