### ISSUE TITLE
Layout/ClassStructure autofix results in incorrect order, refuses to move a constant

### ISSUE THREAD

**Issue by Epigene** [rubocop/rubocop#10449]
Could be same as https://github.com/rubocop/rubocop/issues/9738 but I have an explicit case.
No matter how I tweak the file (remove comments, remove multiline calls, etc.) the constant does not seem to be moved to the upper part of the file, where it started out at!

--------

## Expected behavior

When I run autofix on this file

```rb
# frozen_string_literal: true

class UserAccount < ApplicationRecord
  include DowncasedEmail

  INSIGNIFICANT_CHANGE_FIELDS = [
    :created_at,
    :updated_at,
    *Devise::Models::Trackable.required_fields(self),
  ].map(&:to_s).freeze

  has_one :buyer_profile,
    class_name: "UserBuyerProfile",
    dependent: :destroy  
  has_many :users, -> { order(:type) }, inverse_of: :user_account

  before_save :set_unlock_set_at, if: :unlock_token_changed?  

  delegate :invitations,
    :uberadmin?,
    to: :user

  # devise features
  devise :database_authenticatable, :validatable, :registerable,
    :timeoutable, :recoverable, :trackable,
    :confirmable, :rememberable, :lockable,
    # devise-security features
    :password_archivable, :password_expirable

  attr_accessor :password_required, :skip_confirmation
  
  validates :number_grouping_separator, inclusion: { in: GROUPING_SEPARATORS }
  validate :validate_sso_account, on: :update  
end
```

I expect it to get autofixed to:
```rb
# frozen_string_literal: true

class UserAccount < ApplicationRecord
  include DowncasedEmail

  INSIGNIFICANT_CHANGE_FIELDS = [
    :created_at,
    :updated_at,
    *Devise::Models::Trackable.required_fields(self),
  ].map(&:to_s).freeze

  attr_accessor :password_required, :skip_confirmation

  has_one :buyer_profile,
    class_name: "UserBuyerProfile",
    dependent: :destroy  
  has_many :users, -> { order(:type) }, inverse_of: :user_account

  delegate :invitations,
    :uberadmin?,
    to: :user

  # devise features
  devise :database_authenticatable, :validatable, :registerable,
    :timeoutable, :recoverable, :trackable,
    :confirmable, :rememberable, :lockable,
    # devise-security features
    :password_archivable, :password_expirable

  validates :number_grouping_separator, inclusion: { in: GROUPING_SEPARATORS }
  validate :validate_sso_account, on: :update  

  before_save :set_unlock_set_at, if: :unlock_token_changed?
end
```

## Actual behavior

This is what I get:
```rb
# frozen_string_literal: true

class UserAccount < ApplicationRecord
  include DowncasedEmail

  attr_accessor :password_required, :skip_confirmation
  # devise features
  devise :database_authenticatable, :validatable, :registerable,
    :timeoutable, :recoverable, :trackable,
    :confirmable, :rememberable, :lockable,
    # devise-security features
    :password_archivable, :password_expirable
  delegate :invitations,
    :uberadmin?,
    to: :user
  validates :number_grouping_separator, inclusion: { in: GROUPING_SEPARATORS }
  validate :validate_sso_account, on: :update
  INSIGNIFICANT_CHANGE_FIELDS = [
    :created_at,
    :updated_at,
    *Devise::Models::Trackable.required_fields(self),
  ].map(&:to_s).freeze

  has_one :buyer_profile,
    class_name: "UserBuyerProfile",
    dependent: :destroy
  has_many :users, -> { order(:type) }, inverse_of: :user_account

  before_save :set_unlock_set_at, if: :unlock_token_changed?
end
```

## Steps to reproduce the problem
This is the config for `Layout/ClassStructure` we're using:
```
Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusions:
      - include
      - prepend
      - extend
    attributes:
      - attribute
      - attr_reader
      - attr_writer
      - attr_accessor
      - attr_deprecated
    enum:
      - enum
    associations:
      - belongs_to
      - has_one
      - has_many
      - has_and_belongs_to_many
      - touched_associations
    other_macros:
      - delegate
      - devise
      - state_machine
    validations:
      - validate
      - validates
      - validates_acceptance_of
      - validates_associated
      - validates_confirmation_of
      - validates_exclusion_of
      - validates_format_of
      - validates_inclusion_of
      - validates_length_of
      - validates_numericality_of
      - validates_presence_of
      - validates_uniqueness_of
      - validates_each
      - validate_with
    hooks:
      - before_validation
      - after_validation
      - before_save
      - before_create
      - after_create
      - after_save
      - after_commit
    scopes:
      - scope
  ExpectedOrder:
      - module_inclusions
      - constants
      - attributes
      - enum
      - associations
      - other_macros
      - validations
      - hooks
      - scopes
      - public_class_methods
      - initializer
      - public_methods
      - protected_methods
      - private_methods
```

## RuboCop version
```
$ rubocop -V
1.19.1 (using Parser 3.1.1.0, rubocop-ast 1.16.0, running on ruby 2.7.5 x86_64-darwin20)
  - rubocop-performance 1.11.5
  - rubocop-rails 2.11.3
  - rubocop-rspec 2.4.0
```
