### ISSUE TITLE
Style/RaiseArgs does not catch raise with both `new` and message params

### ISSUE THREAD

**Issue by DocX** [rubocop/rubocop#10621]
## Expected behavior

```rb
raise MyError.new(data: "mydata"), "some error message"
```

According to the documentaion

> The exploded style works identically, but with the addition that it will also suggest constructing error objects when the exception is passed multiple arguments.

it should be offensive when this configuration is used:

```yaml
Style/RaiseArgs:
  Enabled: true
  EnforcedStyle: exploded
  AllowedCompactTypes: []
```

It should be autocorrected to
```rb
raise MyError.new("some error message", data: "mydata")
```

## Actual behavior

No offense is found

## Steps to reproduce the problem

Run rubocop with this configuration:

```yaml
Style/RaiseArgs:
  Enabled: true
  EnforcedStyle: exploded
  AllowedCompactTypes: []
```

on this code:

```rb
raise MyError.new(data: "mydata"), "some error message"
```

## RuboCop version

```
1.29.0 (using Parser 3.1.2.0, rubocop-ast 1.17.0, running on ruby 3.1.0 x86_64-darwin20)
```
