### ISSUE TITLE
Add Layout/ClassStructure refinement support

### ISSUE THREAD

**Issue by bkuhlmann** [rubocop/rubocop#10837]
## Is your feature request related to a problem?

This would be a nice to have, not necessarily a problem. I'd like to suggest that this cop support `using` within `module_inclusion` in order to tap in [refinements](https://www.alchemists.io/articles/ruby_refinements).

## Describe the solution you'd like

Here's what I'd like to see included:

``` yaml
Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - extend
      - include
      - prepend
      - using   # <= This would be new to properly support Ruby Refinements.
```

## Describe alternatives you've considered

There is no automated alternative that I know of.

## Additional context

Nope. This is just a simple request for new module detection.
