### ISSUE TITLE
Add list of exception patterns to Style/NumericLiterals

### ISSUE THREAD

**Issue by dmke** [rubocop/rubocop#10857]
## Is your feature request related to a problem? Please describe.

In a current project, I need to handle identification numbers, which follow the format `<2 digit classification>` `<2 digit region id>` `<4 digit running number>` `<1 digit checksum>` ("[Institutionskennzeichen](https://de.wikipedia.org/wiki/Institutionskennzeichen)", "IK number"), for example `112233334`

## Describe the solution you'd like

I'd like to format them in code as `11_22_3333_4`, but the Style/NumericLiterals cop wants me to format them as `112_233_334`, which is nonsensical.

I also don't want to lose the warnings for ordinary numbers, where grouping the digits in triplets is desirable.

## Describe alternatives you've considered

- `Strict: false` (default) takes offense with `11_22_3333_4`
- `AllowedNumbers: [...]` does not scale
- `Enabled: false` is my current workaround

## Additional context

It would be nice to define (a list of) allowed patterns, for example:

```yaml
Style/NumericLiterals:
  AllowedPatterns:     # list of exceptions, like AllowedNumbers
  - xx_xx_xxxx_x       # either using placeholders
  - \d\d_\d\d_\d{4}_\d # or using regexp
```

I'm not sure if there's precedent for either placeholders or regular expressions in other cops. Maybe there are better alternatives to declare such exceptions.
