### ISSUE TITLE
[Layout/ExtraSpacing] Using emojis in String changes behaviour

### ISSUE THREAD

**Issue by pil0u** [rubocop/rubocop#10961]
Given this object:
```ruby
toto = [
  ["Abc",          1],
  ["Bcdef",        10],
  ["Cdef",         100],
  ["Defghijklm",   100],
  ["Efg ⭐",       1000],
  ["Fghij",        1000],
  ["Ghijklmnopqr", 10]
]
```
I choose to align the numbers using spaces relative to the longest String in the Array, in that case the last one.

I would expect this syntax to be valid, but RuboCop auto-corrects the row containing an emoji like this:
```ruby
toto = [
  ["Abc",          1],
  ["Bcdef",        10],
  ["Cdef",         100],
  ["Defghijklm",   100],
  ["Efg ⭐", 1000],
  ["Fghij",        1000],
  ["Ghijklmnopqr", 10]
]
```

If I remove the emoji, the initial syntax is considered valid and is not corrected:
```ruby
toto = [
  ["Abc",          1],
  ["Bcdef",        10],
  ["Cdef",         100],
  ["Defghijklm",   100],
  ["Efg",          1000],
  ["Fghij",        1000],
  ["Ghijklmnopqr", 10]
]
```

## RuboCop version

```
$ bundle exec rubocop -V
1.35.1 (using Parser 3.1.2.1, rubocop-ast 1.21.0, running on ruby 3.1.2 arm64-darwin21)
  - rubocop-performance 1.14.3
  - rubocop-rails 2.15.2
```

With this exact configuration:
```yml
require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - "**/app/components/**/*"

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails/I18nLocaleTexts:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/StringLiterals:
  EnforcedStyle: double_quotes
```
