### ISSUE TITLE
Naming/MethodParameterName AllowedNames support for `as`

### ISSUE THREAD

**Issue by bkuhlmann** [rubocop/rubocop#10960]
## Describe the solution you'd like

This is a small request for adding `as` to the default list of `AllowedNames`.

## Describe alternatives you've considered

The alternative is to manage my own list of allowed names. Example:

``` yaml
Naming/MethodParameterName:
  AllowedNames:
    - as
    - at
    - by
    - db
    - id
    - in
    - io
    - ip
    - of
    - on
    - os
    - pp
    - to
```

Notice that I include `as` in the list above which is the only exception to the current defaults.

## Additional context

I often find that I'm using `as` as a parameter for functional composition in Ruby where I need to have a parameter that allows me to message an object as a different representation of itself after being operated on. Example (truncated for brevity):

``` ruby
use my_command, as: :to_h
```

The above allows me to delegate to `my_command` with a `#call` message which answers an object that can be converted to a hash via the `as: :to_h` parameter. The use of the `as`  parameter allows me to have short and succinct syntax for pulling this off.
