### ISSUE TITLE
Using inherit_gem causes rubocop to require installation of all dependencies in Gemfile

### ISSUE THREAD

**Issue by mzagaja** [rubocop/rubocop#11012]
I am not sure if this is a bug or feature request, but as a rubocop user we have a gem with our rubocop styles that we include in our Gemfile and then `inherit_from` in our `.rubocop.yml`.

```yaml
AllCops:
  TargetRubyVersion: 2.7.2
  Exclude:
    # files that are generated
    - 'db/seeds.rb'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'bin/*'
    - 'reference/*/*'
    - 'vendor/**/*'
inherit_gem:
  ted_rubocop_rules: rubocop.yml

inherit_from: .rubocop_todo.yml
```
The issue I have is my $EDITOR summons rubocop via the latest version of Ruby, but because of including the `inherit_gem` it wants me to resolve dependcies and install my entire Gemfile in Ruby 3.1.2 even though the bundle uses Ruby 2.7.x via rvm. Removing `inherit_gem` fixes this issue. I don't see why `rubocop` should be coupled to the Gemfile when it `inherits_gem` but work fine when it does not, so would propose not trying to read the Gemfile in this scenario. It should just ask for the specific gem needed.
