### ISSUE TITLE
private method `select' called for true:TrueClass

### ISSUE THREAD

**Issue by Alagaesia93** [rubocop/rubocop#11088]
bundle exec rubocop raises
`private method 'select' called for true:TrueClass`

--------

## Expected behavior

Rubocop should behave normally, show errors / lint, etc

## Actual behavior

After running `bundle exec rubocop` I have the following stacktrace
```
1055 files inspected, 1 offense detected
private method 'select' called for true:TrueClass

          extensions.select { |_, v| (Array(v) & dependent_gems).any? }.keys
                    ^^^^^^^
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.37.0/lib/rubocop/cli/command/suggest_extensions.rb:77:in `all_extensions'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.37.0/lib/rubocop/cli/command/suggest_extensions.rb:89:in `not_installed_extensions'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.37.0/lib/rubocop/cli/command/suggest_extensions.rb:81:in `extensions'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.37.0/lib/rubocop/cli/command/suggest_extensions.rb:18:in `run'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.37.0/lib/rubocop/cli/command.rb:11:in `run'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.37.0/lib/rubocop/cli/environment.rb:18:in `run'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.37.0/lib/rubocop/cli.rb:72:in `run_command'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.37.0/lib/rubocop/cli.rb:84:in `suggest_extensions'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.37.0/lib/rubocop/cli.rb:79:in `block in execute_runners'
<internal:kernel>:90:in `tap'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.37.0/lib/rubocop/cli.rb:79:in `execute_runners'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.37.0/lib/rubocop/cli.rb:48:in `run'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.37.0/exe/rubocop:19:in `block in <top (required)>'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.37.0/exe/rubocop:19:in `<top (required)>'
/Users/<user_name>/.rbenv/versions/3.1.2/bin/rubocop:25:in `load'
/Users/<user_name>/.rbenv/versions/3.1.2/bin/rubocop:25:in `<top (required)>'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:58:in `load'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:23:in `run'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli.rb:483:in `exec'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli.rb:31:in `dispatch'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli.rb:25:in `start'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/exe/bundle:48:in `block in <top (required)>'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/Users/<user_name>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/exe/bundle:36:in `<top (required)>'
/Users/<user_name>/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
/Users/<user_name>/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
```

## Steps to reproduce the problem

Update Rubocop to version 1.37.0
run bundle exec rubocop
See the error in CLI

## RuboCop version

```
1.37.0 (using Parser 3.1.2.1, rubocop-ast 1.22.0, running on ruby 3.1.2) [arm64-darwin21]
  - rubocop-performance 1.15.0
  - rubocop-rspec 2.13.2
```

**Comment by koic** [comment]
Can you provide a reproducible .rubocop.yml?

**Comment by Alagaesia93** [comment]
Sure! Here it is

```
inherit_from:
  - .rubocop_todo.yml
  - node_modules/@prettier/plugin-ruby/rubocop.yml

require:
  - rubocop/cop/internal_affairs
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  SuggestExtensions: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Bundler/GemVersion:
  EnforcedStyle: required
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true
```

If needed I can provide also rubocop_todo.yml, but it's 1200 lines. We inherited a project that had no rubocop for years and slowly trying to get rid of all the alerts.
