### ISSUE TITLE
Add documentation with example of complex but fast docker-compose configuration with --server, caching, etc.

### ISSUE THREAD

**Issue by Mayurifag** [rubocop/rubocop#11128]
Firstly, I would like to appreciate all the rubocop team, who developed this awesome gem! Thank you all!

Here is a topic I would like to start, sorry that its not a feature request actually, but I didn't know where is it better to be started. It's hard for me to set up blazingly fast rubocop configuration on my local docker-compose. When I try to launch rubocop container, it just exits with 0 error code. I've played with nohup/background solutions, `--restart-server`, etc., nothing helped much and rubocop doesn't explain what am I doing wrong. Here is needed lines from my docker-compose:

```yml
version: "3.9"

x-backend: &x-backend
  build:
    context: .
  volumes:
    - .:/app:cached
    - rails_cache:/app/tmp/cache
    - bundle:/bundle
  tmpfs:
    - /tmp
    - /app/tmp/pids

services: 
 #... lots of things ...
  app:
    <<: *x-backend
    command: rails s -p 3000 -b 0.0.0.0

  rubocop:
    <<: *x-backend
    command: rubocop --start-server
    environment:
      RUBOCOP_SERVER_PORT: '22312'
      # RUBOCOP_CACHE_ROOT: /app/tmp/cache/rubocop_cache

volumes:
  bundle:
  rails_cache:
  redis:
  postgres:
```

Furthermore, it would be nice to have information if I have to care about caching when I use rubocop in docker-compose (so, should I have yet another volume or use RUBOCOP_CACHE_ROOT).

And the last thing, information how would one checks specific file with that configuration or how to easy check all the changed files (that rubocop might check) via single alias — that are the topics I would like to have info about.

That's why I think, community needs a big reference about docker-compose usage from documentation site of rubocop, because google gives only outdated rubocop-daemon examples. Thanks in advance 😄
