### ISSUE TITLE
rubocop-i18n plugin specs fail on rubocop 1.38.0

### ISSUE THREAD

**Issue by Fryguy** [rubocop/rubocop#11169]
Nearly all of the specs in the [rubocop-18n plugin](https://github.com/puppetlabs/rubocop-i18n) fail with the same error, `undefined method `disabled' for nil:NilClass`.  This started as of rubocop 1.38.0 and works find in 1.37.1.

The line in question is https://github.com/rubocop/rubocop/blob/v1.38.0/lib/rubocop/comment_config.rb#L94, which implies the registry is `nil` at this point.

## Expected behavior

This plugin's specs all pass with rubocop 1.37.1, and I would expect them to continue to pass.

## Actual behavior

Thousands of spec errors all like the following:

```
  1) RuboCop::Cop::I18n::GetText::DecorateStringFormattingUsingPercent Ds_ decoration with paramaterized %0s behaves like a_detecting_cop has the correct rubocop warning
     Failure/Error: add_offense(message_section, message: "'#{method_name}' function, message string should not contain sprintf style formatting (ie %s)")

     NoMethodError:
       undefined method `disabled' for nil:NilClass
     Shared Example Group: "a_detecting_cop" called from ./spec/rubocop/cop/i18n/gettext/decorate_string_formatting_using_percent_spec.rb:44
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rubocop-1.38.0/lib/rubocop/comment_config.rb:94:in `inject_disabled_cops_directives'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rubocop-1.38.0/lib/rubocop/comment_config.rb:78:in `analyze'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rubocop-1.38.0/lib/rubocop/comment_config.rb:45:in `cop_disabled_line_ranges'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rubocop-1.38.0/lib/rubocop/comment_config.rb:38:in `cop_enabled_at_line?'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rubocop-1.38.0/lib/rubocop/cop/base.rb:429:in `enabled_line?'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rubocop-1.38.0/lib/rubocop/cop/base.rb:127:in `add_offense'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rubocop-1.38.0/lib/rubocop/cop/cop.rb:29:in `add_offense'
     # ./lib/rubocop/cop/i18n/gettext/decorate_string_formatting_using_percent.rb:37:in `on_send'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:100:in `public_send'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:100:in `block (2 levels) in trigger_responding_cops'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:160:in `with_cop_error_handling'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:99:in `block in trigger_responding_cops'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:98:in `each'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:98:in `trigger_responding_cops'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:69:in `on_send'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:20:in `walk'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:86:in `investigate'
     # ./spec/shared_functions.rb:6:in `investigate'
     # ./spec/rubocop/cop/i18n/gettext/decorate_string_formatting_using_percent_spec.rb:7:in `block (2 levels) in <top (required)>'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:365:in `run'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:529:in `block in run_owned_hooks_for'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:528:in `each'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:528:in `run_owned_hooks_for'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:615:in `block in run_example_hooks_for'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:614:in `reverse_each'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:614:in `run_example_hooks_for'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:484:in `run'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:505:in `run_before_example'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:261:in `block in run'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:486:in `block in run'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:486:in `run'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:259:in `run'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:642:in `map'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:642:in `run_examples'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:607:in `run'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `block in run'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `map'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `run'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `block in run'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `map'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `run'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `map'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/reporter.rb:74:in `report'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:115:in `run_specs'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:89:in `run'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:71:in `run'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/rspec-core-3.12.0/exe/rspec:4:in `<top (required)>'
     # /Users/jfrey/.gem/ruby/2.7.2/bin/rspec:23:in `load'
     # /Users/jfrey/.gem/ruby/2.7.2/bin/rspec:23:in `<top (required)>'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:63:in `load'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:63:in `kernel_load'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:28:in `run'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/bundler-2.2.24/lib/bundler/cli.rb:475:in `exec'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/bundler-2.2.24/lib/bundler/cli.rb:31:in `dispatch'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/bundler-2.2.24/lib/bundler/cli.rb:25:in `start'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/bundler-2.2.24/exe/bundle:49:in `block in <top (required)>'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/bundler-2.2.24/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
     # /Users/jfrey/.gem/ruby/2.7.2/gems/bundler-2.2.24/exe/bundle:37:in `<top (required)>'
     # /Users/jfrey/.gem/ruby/2.7.2/bin/bundle:23:in `load'
     # /Users/jfrey/.gem/ruby/2.7.2/bin/bundle:23:in `<main>'
```

## Steps to reproduce the problem

- Clone rubocop-i18n (current `HEAD` is https://github.com/puppetlabs/rubocop-i18n/commit/92ef8f477249b39af0d6db40189ad590542a7338)
- `bundle update`
- `bundle exec rake spec`

## RuboCop version

```
1.38.0 (using Parser 3.1.2.1, rubocop-ast 1.23.0, running on ruby 2.7.2) [x86_64-darwin19]
```
