### ISSUE TITLE
Add option to exclude methods for Style/DocumentationMethod cop

### ISSUE THREAD

**Issue by blackst0ne** [rubocop/rubocop#11504]
## Is your feature request related to a problem? Please describe.

The [Style/DocumentationMethod](https://github.com/rubocop/rubocop/blob/master/lib/rubocop/cop/style/documentation_method.rb) checks for all the public methods including `initialize`.   
The constructor doesn't have to have a documentation comment.

## Describe the solution you'd like

Add an option for the cop to exclude method names.  E.g. 

```
Style/DocumentationMethod:
  Enabled: true
  Include:
    - 'app/policies/**/*.rb'
  ExcludedMethods:
  - 'initialize'
  - 'foo'
  - 'bar'
```

## Describe alternatives you've considered

An alternative is to disable the cop by the `rubocop:disable` comment around wanted methods.
