### ISSUE TITLE
Layout/LineLength triggers on long URI in comment

### ISSUE THREAD

**Issue by jcoyne** [rubocop/rubocop#11734]
```
Offenses:

app/models/purl.rb:53:159: C: Layout/LineLength: Line is too long. [159/132]
  # https://github.com/sul-dlss/searchworks_traject_indexer/blob/64359399e8f670ed414b1c56c648dc9b95ad6bad/lib/traject/readers/kafka_purl_fetcher_reader.rb#L26
```

I have the cop configured thusly:
```yaml
# Configuration parameters: AllowURI, URISchemes.
Layout/LineLength:
  Max: 132
  AllowURI: true
```

I would expect that `AllowURI: true` would permit the long comment as it only contains a URI.

**Comment by nobuyo** [comment]
Can you give us the minimum code and version info to reproduce?
I could not reproduce it with the following code:

```yaml
# rubocop.yml

Layout/LineLength:
  Max: 132
  AllowURI: true
```

```rb
# frozen_string_literal: true

# https://github.com/sul-dlss/searchworks_traject_indexer/blob/64359399e8f670ed414b1c56c648dc9b95ad6bad/lib/traject/readers/kafka_purl_fetcher_reader.rb#L26
foo
```

```console
$ bundle exec rubocop test.rb
Inspecting 1 file
.

1 file inspected, no offenses detected

$ bundle exec rubocop -V
1.48.1 (using Parser 3.2.1.0, rubocop-ast 1.27.0, running on ruby 3.2.0) [arm64-darwin21]
```

I believe `AllowURI` is enabled by default, is it disabled somewhere else?
https://github.com/rubocop/rubocop/blob/master/config/default.yml#L1051
