### ISSUE TITLE
Inline disabling of Rubocop rules

### ISSUE THREAD

**Issue by morgoth** [rubocop/rubocop#11743]
To keep .rubocop.yml file compact it would be helpful to be able to disable rules by just one line, so instead of:
```yaml
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
# ... many others
```
have simple:
```yaml
Metrics/AbcSize: false
# or maybe
Metrics/BlockLength: Disabled
# ... many others
```

That could shrink the file even by half.
