### ISSUE TITLE
Fix Style/MethodCallWithArgsParentheses error with guarded standalone pattern

### ISSUE THREAD

**Issue by bkuhlmann** [rubocop/rubocop#12134]
## Expected behavior

I'd expect the following to not cause an error since the parenthesis are required:

``` ruby
demo = {a: 1, b: 2, c: 3}
puts "Found." if demo.values_at(:a, :c) in Integer, Integer
```

## Actual behavior

The following error will appear:

``` ruby
C: [Correctable] Style/MethodCallWithArgsParentheses: Omit parentheses for method calls with arguments. (https://rubystyle.guide#method-invocation-parens)
puts "Found." if demo.values_at(:a, :c) in Integer, Integer
                               ^^^^^^^^
```

Letting RuboCop auto-correct the error -- by removing the parenthesis -- will result in the following syntax error:

``` 
syntax error, unexpected `in', expecting end-of-input
> 17  puts "Found." if demo.values_at :a, :c in Integer, Integer

syntax error, unexpected `in', expecting end-of-input (SyntaxError)
...d." if demo.values_at :a, :c in Integer, Integer
...                             ^~
```

## Steps to reproduce the problem

Use the following RuboCop configuration:

``` yaml
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInChaining: true
  AllowParenthesesInMultilineCall: true
  IgnoreMacros: false
```

Use the following script:

``` ruby
#! /usr/bin/env ruby
# frozen_string_literal: true

# Save as `demo`, then `chmod 755 demo`, and run as `./demo`.

demo = {a: 1, b: 2, c: 3}
puts "Found." if demo.values_at(:a, :c) in Integer, Integer
```

## RuboCop version

```
$ [bundle exec] rubocop -V
1.56.0 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 3.2.2) [arm64-darwin22.4.0]
  - rubocop-capybara 2.18.0
  - rubocop-factory_bot 2.23.1
  - rubocop-packaging 0.5.2
  - rubocop-performance 1.19.0
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.23.2
  - rubocop-thread_safety 0.5.1
```
