### ISSUE TITLE
--auto-gen-config should generate exclusion sets when metric is overridden

### ISSUE THREAD

**Issue by luke-hill** [rubocop/rubocop#12179]
--------

## Expected behavior

Running rubocop --auto-gen-config should then produce a `rubocop` run with 0 issues. Ideally this would be generating exclusion files for offenses so as not to conflict

## Actual behavior

Running rubocop --auto-gen-config still leaves 8 issues
This is because both the regular / override file have `Max` settings for some metrics

```
# .rubocop.yml - snippet

Metrics/AbcSize:
  Max: 41

Metrics/ClassLength:
  Max: 375

Layout/LineLength:
  Max: 200

Metrics/ModuleLength:
  Max: 135
```

```
# .rubocop_todo.yml - snippet

# Offense count: 2
# Configuration parameters: AllowedMethods, AllowedPatterns, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 73

# Offense count: 1
# Configuration parameters: CountComments, CountAsOne.
Metrics/ClassLength:
  Max: 382

# Offense count: 9
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/CyclomaticComplexity:
  Max: 12

# Offense count: 4
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
Metrics/MethodLength:
  Max: 72

# Offense count: 1
# Configuration parameters: CountComments, CountAsOne.
Metrics/ModuleLength:
  Max: 177
```

## Steps to reproduce the problem

Generate a rubocop / autogen file with the above settings

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler.
If you see extension cop versions (e.g. `rubocop-performance`, `rubocop-rspec`, and others)
output by `rubocop -V`, include them as well. Here's an example:

```
1.56.2 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 3.2.2) [x86_64-linux]
  - rubocop-capybara 2.18.0
  - rubocop-packaging 0.5.2
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.23.2
```
