### ISSUE TITLE
rubocop incorrectly prompts to install rubocop-rails plugin when it is already installed

### ISSUE THREAD

**Issue by matthewhively** [rubocop/rubocop#12277]
## Expected behavior

Rubocop runs as normal without any extra messages. Like it did in version 1.31.0

## Actual behavior

Rubocop prints out
```
Tip: Based on detected gems, the following RuboCop extension libraries might be helpful:
  * rubocop-rails (https://rubygems.org/gems/rubocop-rails)

You can opt out of this message by adding the following to your config (see https://docs.rubocop.org/rubocop/extensions.html#extension-suggestions for more options):
  AllCops:
    SuggestExtensions: false
```

extra debug info
```
rubocop --debug
For railsapp: configuration from railsapp/.rubocop.yml
configuration from .rvm/gems/ruby-2.7.8/gems/rubocop-performance-1.19.1/config/default.yml
configuration from .rvm/gems/ruby-2.7.8/gems/rubocop-performance-1.19.1/config/default.yml
Default configuration from .rvm/gems/ruby-2.7.8/gems/rubocop-1.57.1/config/default.yml
configuration from .rvm/gems/ruby-2.7.8/gems/rubocop-rails-2.21.2/config/default.yml
configuration from .rvm/gems/ruby-2.7.8/gems/rubocop-rails-2.21.2/config/default.yml
Inheriting configuration from railsapp/.rubocop/resolved.yml
Inheriting configuration from railsapp/.rubocop/wip.yml
Inheriting configuration from railsapp/.rubocop/tbd.yml
Inheriting configuration from railsapp/.rubocop_todo.yml
```

## Steps to reproduce the problem

Install rubocop and rubocop rails latest version in a rails application.
Run rubocop on your project.
Observe the printouts.

NOTE: if it matters, my main rubocop.yml file:
```
inherit_from:
  - .rubocop/resolved.yml
  - .rubocop/wip.yml
  - .rubocop/tbd.yml
  - .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7 
  SuggestExtensions:
    rubocop-rspec: false
    rubocop-capybara: false
```

## RuboCop version

```
rubocop -V
1.57.1 (using Parser 3.2.2.4, rubocop-ast 1.29.0, running on ruby 2.7.8) [x86_64-darwin21]
  - rubocop-performance 1.19.1
  - rubocop-rails 2.21.2
```
