### ISSUE TITLE
Bug in Style/PredicateName when method legitimately starts with 'is'

### ISSUE THREAD

**Issue by jfelchner** [rubocop/rubocop#1245]
This is a pretty funny bug.  Definitely made me smile when I got it. :smile:

I have a method:

``` ruby
def issue_specified?
  # Codez
end
```

With a rubocop configuration like so:

``` yaml
PredicateName:
  NamePrefixBlacklist:
    - 'is'
    - 'was'
    - 'have'
```

When I run it against my code I get:

```
C: Style/PredicateName: Rename issue_specified? to sue_specified?
```

I'd assume that the fix is not to change the `NamePrefixBlacklist` to `is_`, but feel free to tell me I'm wrong.
