### ISSUE TITLE
Fix Style/MethodCallWithArgsParentheses for case expressions

### ISSUE THREAD

**Issue by bkuhlmann** [rubocop/rubocop#12524]
## Expected behavior

Hello. 👋 I would expect the following to not be flagged as an issue:

``` ruby
Unit = lambda do |duration, range: RANGE|
  case duration
    when range.fetch(:nanoseconds) then "ns"
    when range.fetch(:microseconds) then "µs"
    when range.fetch(:milliseconds) then "ms"
    when range.fetch(:seconds) then "s"
    else "m"
  end
end
```

## Actual behavior

Given the above, RuboCop flags the use of parenthesis for `#fetch` but if you remove the parenthesis, you'll end up with a `SyntaxError`:

``` 
syntax error, unexpected symbol literal, expecting `then' or ',' or ';' or '\n'
```

## Steps to reproduce the problem

You'll need this RuboCop configuration to run against the above code snippet:

``` 
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInChaining: true
  AllowParenthesesInMultilineCall: true
  IgnoreMacros: false
```

## RuboCop version

```
1.58.0 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.2.2) [arm64-darwin22.4.0]
  - rubocop-capybara 2.19.0
  - rubocop-factory_bot 2.24.0
  - rubocop-packaging 0.5.2
  - rubocop-performance 1.19.1
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.25.0
  - rubocop-thread_safety 0.5.1
```
