### ISSUE TITLE
`Style/MethodCallWithArgsParentheses` and `Style/SuperWithArgsParentheses` cause an infinite loop

### ISSUE THREAD

**Issue by rickselby** [rubocop/rubocop#12596]
When omitting parentheses with `Style/MethodCallWithArgsParentheses`, it is not possible to also use `Style/SuperWithArgsParentheses` as this causes an infinite loop

--------

## Expected behavior

Rubocop does not crash! And probably leaves `super` with parentheses.

There could possibly be support in `Style/MethodCallWithArgsParentheses` for a list of methods that are allowed parentheses when `EnforcedStyle` is `omit_parentheses`? It's possible to do the reverse when enforcing parentheses.

## Actual behavior

```
Infinite loop detected in code.rb and caused by Style/SuperWithArgsParentheses -> Style/MethodCallWithArgsParentheses
```

## Steps to reproduce the problem

`.rubocop.yml`
```
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses

Style/SuperWithArgsParentheses:
  Enabled: true
```

`code.rb`
```
class Class1
  def initialize(foo)
    @foo = foo
  end
end

class Class2 < Class1
  def initialize(foo)
    super foo
    bar
  end
end
```

## RuboCop version

```
$ rubocop -V
1.59.0 (using Parser 3.3.0.0, rubocop-ast 1.30.0, running on ruby 3.3.0) +server [x86_64-linux]
```
