### ISSUE TITLE
Infinite loop with `Layout/RedundantLineBreak` and `Style/SingleLineDoEndBlock`

### ISSUE THREAD

**Issue by rickselby** [rubocop/rubocop#12597]
## Expected behavior

Rubocop fixes the cops correctly

## Actual behavior

> Infinite loop detected in code.rb and caused by Layout/RedundantLineBreak -> Style/BlockDelimiters, Style/SingleLineDoEndBlock -> Layout/BlockAlignment, Layout/IndentationWidth, Layout/RedundantLineBreak, Layout/TrailingWhitespace, Style/BlockDelimiters -> Layout/IndentationWidth, Layout/RedundantLineBreak -> Layout/IndentationWidth, Layout/RedundantLineBreak

## Steps to reproduce the problem

`.rubocop.yml`
```
Layout/RedundantLineBreak:
  Enabled: true
  InspectBlocks: true

Style/SingleLineDoEndBlock:
  Enabled: true
```

`code.rb`
```
def foo
  a.each do |x|
    x.each do |y|
      bar y
    end
  end
end
```

## RuboCop version

```
$ rubocop -V
1.59.0 (using Parser 3.3.0.0, rubocop-ast 1.30.0, running on ruby 3.3.0) [x86_64-linux]
```
