### ISSUE TITLE
False positives for Lint/UnusedBlockArgument when using parser_prism

### ISSUE THREAD

**Issue by Darhazer** [rubocop/rubocop#12757]
When using `parser_prism`, `Lint/UnusedBlockArgument` doesn't recognise block argument being used when short hash syntax is used.

```ruby
[1,2,3].map { |x| foo(x:) }
```

The code above does not produce offence with `parser_whitequark` but with `parser_prism` says `Lint/UnusedBlockArgument: Unused block argument - x. You can omit the argument if you don't care about it.`

## RuboCop version

1.62.0 (using Prism 0.24.0, rubocop-ast 1.31.1, running on ruby 3.3.0) [arm64-darwin23]
configured as

```yaml
AllCops:
    ParserEngine: parser_prism
    TargetRubyVersion: 3.3
```
