### ISSUE TITLE
Add `*.opal` to default inclusions 

### ISSUE THREAD

**Issue by lloeki** [rubocop/rubocop#1396]
`.opal` is an alternative extension for [Opal](http://opalrb.org). While it is possible to call opal files with `.rb`, it has side effects in Rails, so `.opal` is preferred in that situation.

As a workaround it is necessary to add this to `.rubocop.yml`:

``` yml
AllCops:
    Include:
        - '**/*.opal'
```

Adding `*.opal` to default inclusions would make it work out of the box.
