### ISSUE TITLE
Configuration option for `Layout/HashAlignment` to ensure a minimum indentation for all members of the hash.

### ISSUE THREAD

**Issue by Zopolis4** [rubocop/rubocop#14007]
## Is your feature request related to a problem? Please describe.

The following code, and code structured similarly to it, appears multiple times throughout my codebase:
```ruby
binary_sha256({
      i686: 'd24b37d653b0c8a57373f10b8431ad26691a196f0d9d9e5ba45495c65b9a60eb',
    x86_64: '5a2837b20f71f04a5d5791adf96c5c78795e1a8487ee564795779e7c91fb9a01'
})
```

rubocop autocorrects it to this:
```ruby
binary_sha256({
  i686: 'd24b37d653b0c8a57373f10b8431ad26691a196f0d9d9e5ba45495c65b9a60eb',
x86_64: '5a2837b20f71f04a5d5791adf96c5c78795e1a8487ee564795779e7c91fb9a01'
})
```

which is not what i'd like.

## Describe the solution you'd like

A configuration option for `Layout/HashAlignment` that ensures all members of the hash have a minimum indentation (in my case, 2) that prevents them from being flush with the end of the hash, but also allows the ability to trim down on excess indentation above this threshold.

simply put:
```
Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - separator
  EnforcedColonStyle:
    - separator
  MinimumIndentation: 2 # or maybe it would be dependent on IndentationWidth or something idk
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
```

which, when run on this code:
```ruby
binary_sha256({
      i686: 'd24b37d653b0c8a57373f10b8431ad26691a196f0d9d9e5ba45495c65b9a60eb',
    x86_64: '5a2837b20f71f04a5d5791adf96c5c78795e1a8487ee564795779e7c91fb9a01'
})
```

corrects it into this:
```ruby
binary_sha256({
    i686: 'd24b37d653b0c8a57373f10b8431ad26691a196f0d9d9e5ba45495c65b9a60eb',
  x86_64: '5a2837b20f71f04a5d5791adf96c5c78795e1a8487ee564795779e7c91fb9a01'
})
```

this is a rough outline of the behavior i'm trying to achieve:
```ruby
# good
{
  aaaaaaa: 1,
   aaaaaa: 2,
     aaaa: 3,
   aaaaaa: 4,
}

# good
{
  aaaaaaa: 1,
   aaaaaa: 2,
   aaaaaa: 4,
}

# bad
{
    aaaaaa: 4,
}
# should be corrected to
{
  aaaaaa: 4,
}

# bad
{
  aaaa: 3,
aaaaaa: 4,
}
# should be corrected to
{
    aaaa: 3,
  aaaaaa: 4,
}
```

## Describe alternatives you've considered

manually correcting the code to the format I desire (rubocop formats it back to the way I don't want, so I have to disable both hash alignment cops which then lets other formatting issues go unnoticed)

there is also a possibility this is an available configuration option, and I simply did not notice it. I did check thoroughly before opening this issue, but if it turns out I have missed something I apologize.

## Additional context

These are the relevant parts of my rubocop config:
```
Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - separator
  EnforcedColonStyle:
    - separator

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
```
