### ISSUE TITLE
Bad autocorrect in `Layout/HashAlignment` when multiple styles are allowed

### ISSUE THREAD

**Issue by vlad-pisanov** [rubocop/rubocop#14072]
Consider
```ruby
{
  foo:     1,
  'bar' => 2,
}
```
and configuration
```yaml
Layout/HashAlignment:
  EnforcedColonStyle: [table, key]
  EnforcedHashRocketStyle: [table, key]
```
autocorrecting with `-a` produces the mangled:
```ruby
{
  foo:   1,
  '=> 2,
}
```

(I believe the order of the styles matters here: `[table, key]` produces mangled code, but `[key, table]` does not)

```sh
1.75.1 (using Parser 3.3.7.3, Prism 1.4.0, rubocop-ast 1.43.0, analyzing as Ruby 3.3, running on ruby 3.3.2) [x86_64-darwin24]
  - rubocop-minitest 0.37.1
  - rubocop-performance 1.24.0
  - rubocop-rails 2.30.3
  - rubocop-factory_bot 2.27.1
```
