### ISSUE TITLE
Deprecation warning on `dir/**/*` style pattern

### ISSUE THREAD

**Issue by kytrinyx** [rubocop/rubocop#1418]
As of today I started receiving a deprecation warning, e.g.:

``` plain
Deprecated pattern style '/Users/kytrinyx/code/exercism/x-api/problems/**/*' in /Users/kytrinyx/code/exercism/x-api/.rubocop.yml
```

It does not specify what style should be used to replace this.

The change appears to have been introduced in d57350f902e438efc0c64ad61bf36e85f52e6303, but I can't tell if it was intentional. [This comment](https://github.com/bbatsov/rubocop/blob/d57350f902e438efc0c64ad61bf36e85f52e6303/lib/rubocop/path_util.rb#L24) mentions the pattern, but I can't figure out if it means that the pattern is intended to be deprecated or not.

The relevant section of my `.ruboconf.yml` file is:

``` yaml
AllCops:
  Exclude:
    - 'problems/**/*'
    - 'test/fixtures/**/*'
    - 'bin/*'
    - 'vendor/**/*'
```

The README currently encourages the use of the pattern, saying:

> **Note**: The pattern `config/*`\* will match any file recursively under config, but this pattern style is deprecated and should be replaced by `config/**/*`.
