### ISSUE TITLE
Deadlock on this enforced StringLiterals+InInterpolation style

### ISSUE THREAD

**Issue by lloeki** [rubocop/rubocop#1421]
```
Style/StringLiterals:
    EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
    EnforcedStyle: single_quotes
```
