### ISSUE TITLE
Infinite loop in autocorrect when running Style/SpaceAfterSemicolon & Style/SpaceInsideBlockBraces

### ISSUE THREAD

**Issue by andreaseger** [rubocop/rubocop#1501]
given this snippet

``` ruby
3.times{ something;other_thing;}
```

with this config for SpaceInsideBlockBraces

``` yml
SpaceInsideBlockBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: false
```

this command will be stuck in an infinite loop `rubocop -a --only Style/SpaceAfterSemicolon,Style/SpaceInsideBlockBraces foo.rb`

(using `0.28.0 (using Parser 2.2.0.pre.8, running on ruby 2.1.2 x86_64-linux)`)
