### ISSUE TITLE
can't ignore *.rb.swp files

### ISSUE THREAD

**Issue by Kagetsuki** [rubocop/rubocop#272]
I can't get rubocop to ignore my vim .swp files and it's parsing them because they include .rb. I've tried adding *.swp to Excludes under AllCops but it doesn't seem to catch. Perhaps I'm doing it wrong?

``` yml
AllCops:
    Includes:
    Excludes:
        - *.swp
```
