### ISSUE TITLE
Cannot exclude vendor/ folder

### ISSUE THREAD

**Issue by lenntt** [rubocop/rubocop#288]
I'm using bundler, and all my gems are installed in projects_folder/vendor/ (including rubocop).
I've been succesfully excluding folders, but somehow I'm not able to exclude the vendor folder. Maybe it has something to do with rubocop being in it???

I think I've tried everything, like

```
vendor/**
'**/vendor/**'
vendor/**/*
```

etc.

(furthermore: in the code in `Rubocop::Config#match_path?` I see that pattern can either be a string or a regex... but how to define a regex in the rubocop.yml?)

**Comment by bogdan8** [comment]
@jonas054 
Hi, I launch a rubocop through a Travise in the github
but for some reason it checks the folder `vendore` Maybe you know why?

**Travis:**
```
script: bundle exec rspec spec && bundle exec rubocop --config .rubocop.yml

```

**.rubocop.yml**
```
AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - '**/bin/spring'
    - '**/bin/setup'
    - '**/bin/rake'
    - '**/bin/rails'
    - '**/db/schema.rb'
    - 'client/**/**'
    - 'config/**/**'
    - 'db/**/**'
    - 'bin/**'
    - 'app/models/role.rb'
    - 'vendor/*'
Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
  ExcludedMethods: ['included']
```

![screenshot from 2018-07-15 15-37-06](https://user-images.githubusercontent.com/12710600/42734011-024c5c8e-8845-11e8-9e6c-c48ee32abede.png)
