### ISSUE TITLE
['AllCops']['Excludes'] ignored from configuration file passed via -c

### ISSUE THREAD

**Issue by fancyremarker** [rubocop/rubocop#620]
Between v0.14.0 and v0.15.0, the behavior changed when specifying a value for ['AllCops']['Excludes'] in an external configuration file passed via the "-c" command line option. Specifically, given the following YAML:

``` yaml
# /path/to/rubocop.yml
AllCops:
  Excludes:
    - !ruby/regexp /\/db\/schema\.rb$/
```

And running `rubocop -c /path/to/rubocop.yml`... In v0.14.0, db/schema.rb would be ignored, but in v0.15.0, db/schema.rb is NOT ignored.

Is this a bug, or intended? If intended, what is a workaround?

Thanks!
