### ISSUE TITLE
Weird Include/Exclude behavior with executable ruby files

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubocop/rubocop#8145]
Maybe this is expected behavior, in that case I'm happy to add the required exclusions to make this work the way I want. But it certainly surprised me so I figured I would open an issue.

Consider the following project setup

```
$ tree -a
.
├── bin
│   └── foo
├── foo.rb
├── .rubocop_subproject.yml
├── .rubocop.yml
└── subproject
    └── foo.rb

2 directories, 5 files
```

With the following content for each file

##### bin/foo (executable)

```ruby
#!/usr/bin/env ruby

puts "I'm a ruby script"
```

##### .rubocop_subproject.yml

```yaml
AllCops:
  DisabledByDefault: true
  Include:
    - 'subproject/**/*.rb'
```

##### .rubocop.yml

```yaml
AllCops:
  DisabledByDefault: true
  Exclude:
    - 'subproject/**/*.rb'
```

## Expected behavior

```
$ rubocop -L
bin/foo
foo.rb

$ rubocop -c .rubocop_subproject.yml -L
subproject/foo.rb
```

## Actual behavior

```
$ rubocop -L
bin/foo
foo.rb

$ rubocop -c .rubocop_subproject.yml -L
bin/foo
subproject/foo.rb
```

## Steps to reproduce the problem

I think it should be pretty easy copying the previous layout.

## RuboCop version

```
$ [bundle exec] rubocop -V
0.85.1 (using Parser 2.5.1.2, running on ruby 2.5.1 x86_64-linux)
```
