### ISSUE TITLE
Github Ruby style guide

### ISSUE THREAD

**Issue by dpo** [rubocop/rubocop#823]
Hi. I'm wondering if it's possible to configure rubocop to adhere closely to the [Github Ruby style guide](https://github.com/styleguide/ruby). Perhaps somebody already has a working config?!

Thanks for a great project!

**Comment by justin808** [comment]
Did any of you every create a github ruby config file?

**Comment by parkr** [comment]
Nope :/

**Comment by justin808** [comment]
@parkr In case anybody asks, here's mine:

I'm adding it to my tutorial on react-webpack-rails: 

https://github.com/justin808/react-webpack-rails-tutorial/pull/29

```yml
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'client/node_modules/**/*'
    - 'bin/**/*'

Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
```
