### ISSUE TITLE
Add configuration parameter to SpaceAroundEqualsInParameterDefault

### ISSUE THREAD

**Issue by jonas054** [rubocop/rubocop#839]
Extracted from #838.

Add in `config/default.yml`

``` yaml
SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space
  SupportedStyles:
    - space
    - no_space
```

And then code to support it.
