### ISSUE TITLE
Rubocop fights with it self regarding TrailingComma vs SpaceInsideBrackets [Lock-up]

### ISSUE THREAD

**Issue by danlo** [rubocop/rubocop#908]
Rubocop 0.19.1

.rubocop.yml

``` yaml
TrailingComma:
  EnforcedStyleForMultiline: comma
  SupportedStyles:
    - comma
    - no_comma
```

``` ruby
# test.rb
profile_options = {
  formats: [:flat, :graph_html, :call_tree]
}

puts profile_options
```

rubocop -Da test.rb

This will lock up rubocop in an endless fight.

Thank you!  I love this!
