### ISSUE TITLE
Style/MethodCallWithArgsParentheses doesn't respect endless class method parethensis

### ISSUE THREAD

**Issue by bkuhlmann** [rubocop/rubocop#9707]
## Expected behavior

When using the following Rubocop configuration (note the enforced style):

``` yaml
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInChaining: true
  AllowParenthesesInMultilineCall: true
  IgnoreMacros: false
```

I would not expect to have a violation for the following contrived code sample (note the use of the endless class method for `.call`):

``` ruby
# frozen_string_literal: true

require "http"

class Example
  def self.call = new(client: HTTP)

  def initialize client: HTTP
    @client = client
  end

  private

  attr_reader :client
end
```

In the above scenario, the parenthesis _can't be removed_ because the endless method would no longer be syntactically correct for Ruby 3.0.0.

## Actual behavior

When using the above configuration, you'll end up with this error:

``` 
Inspecting 1 file
C

Offenses:

/Users/bkuhlmann/Engineering/Misc/snippet.rb:6:22: C: [Correctable] Style/MethodCallWithArgsParentheses: Omit parentheses for method calls with arguments. (https://rubystyle.guide#method-invocation-parens)
  def self.call = new(client: HTTP)
                     ^^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense auto-correctable
```

## Steps to reproduce the problem

To reproduce this issue, use the above Rubocop configuration and Ruby code snippet saved as `snippet.rb`. You can then then run Rubocop as follows to reproduce the error:

``` 
rubocop snippet.rb
```

## RuboCop version

```
rubocop -V
1.12.1 (using Parser 3.0.1.0, rubocop-ast 1.4.1, running on ruby 3.0.1 arm64-darwin20)
  - rubocop-performance 1.10.2
  - rubocop-rake 0.5.1
  - rubocop-rspec 2.2.0
```
