### ISSUE TITLE
department-level enable/disable does not work

### ISSUE THREAD

**Issue by jaymzh** [rubocop/rubocop#9752]
**UPDATE**: On further investigation, department-level enable/disable just doesn't work.

The docs [say this should work works](https://docs.rubocop.org/rubocop/1.13/configuration.html):

```
All cops are then disabled by default. Only cops appearing in user configuration files are enabled. Enabled: true does not have to be set for cops in user configuration. They will be enabled anyway. It is also possible to enable entire departments by adding for example

Style:
  Enabled: true
```

But it turns out this doesn't work at all. This is because `Style` is seen as an "invalid" config in Config::Validator.validate() and thus ignored. :/

--------

# Original ticket (for context)

This is probably not a rubocop bug, but I dunno where else to ask.

In the [cookstyle](https://github.com/chef/cookstyle/) project, we just sit ontop of the awesomeness that is Rubocop, and define a bunch of our own Cops and departments.

However, departments defined by our own cops don't seem to be enable-able the way, say `Style` is. So I can do this:

```yaml
AllCops:
  DisabledByDefault: true

Style:
  Enabled: true
```

But what I can't do is (`Chef/Correctness` here is a department, you can see code for cops in that department [here](https://github.com/chef/cookstyle/tree/master/lib/rubocop/cop/chef/correctness)).

```yaml
AllCops:
  DisabledByDefault: true

Chef/Correctness:
  Enabled: true
```

or even:
```yaml
AllCops:
  DisabledByDefault: true

Chef:
  Enabled: true
```

What's really strange is that in robocop I don't see any special setup for the `Style` or `Layout` etc _modules_, so I would think this would "just work"... but it doesn't seem to. When I we try we get:

```
Warning: Chef/Correctness does not support Enabled parameter.

Supported parameters are: 

  - StyleGuideBaseURL
```

If I do just `Chef`, then I get:

```
Error: unrecognized cop Chef found in .cookstyle.yml
```

I'm sure is some minor dumb thing we're doing or not doing that's preventing this from working like the rubocop-built-in departments.

Any help would be greatly appreciated.
