### ISSUE TITLE
Layout/HashAlignment, table, vs implicit last argument

### ISSUE THREAD

**Issue by zverok** [rubocop/rubocop#9858]
Test case:
```ruby
# test.rb
# frozen_string_literal: true

def foo
  puts('test', a: 1, b: 2,
c: 3)
end
```
```yaml
# .rubocop.yml
Layout/HashAlignment:
  Enabled: true
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: always_inspect
```

When running rubocop, this produces no offenses, while alignment is "obviously" off. 
The case is important as autocorrecting `LineLength` might produce _a lot_ of cases like that, and in large codebase it is not always easy to spot on the same PR.
