### ISSUE TITLE
not including parent level dir

### ISSUE THREAD

**Issue by ff-apujari** [rubocop/rubocop#990]
``` yml
AllCops:
  Include:
    - '../other_rails_engine/**'

```

seems it is not including a dir above even when specified. ../other_rails_engine is a rails app in gem form that we are using commonly across several apps

If I comment this line or not, the count of offenses coming same, nor do I find a file listed in the offenses belonging to the other_rails_engine
