### ISSUE TITLE
Bug in Layout/LineEndStringConcatenationIndentation

### ISSUE THREAD

**Issue by robotdana** [rubocop/rubocop#9916]
When the EnforcedStyle is aligned, and a concatenated string isn't assigned or a method arg, the second string line is indented instead. 

--------

## Expected behavior

```
block do
  'string' \
  'string'
end
```

## Actual behavior

```
block do
  'string' \
    'string'
end
```

## Steps to reproduce the problem

Run rubocop -A on this file
```
# frozen_string_literal: true

block do
  'string' \
  'string'
end

puts 'string' \
     'string'

'string' \
'string'
```

with this .rubocop.yml
```
AllCops:
  NewCops: enable

Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: aligned
```

and expect no changes

## RuboCop version

1.18.2
