### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by geordee** [rubocop/rubocop#992]
wihtout to without

``` yaml
SpaceBeforeFirstArg:
  Description: >-
                 Put a space between a method name and the first argument
                 in a method call wihtout parentheses.
```
