### ISSUE TITLE
`Style/TrailingCommaInArrayLiteral` vs `Style/HashAsLastArrayItem`

### ISSUE THREAD

**Issue by zverok** [rubocop/rubocop#9939]
Code:
```ruby
x = [
  1,
  {
    a: 1,
    b: 2,
  },
]
```
`.rubocop.yml`:
```yml
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/HashAsLastArrayItem:
  EnforcedStyle: no_braces
```

Run `rubocop -a`

## Expected behavior

```ruby
x = [
  1,
  a: 1,
  b: 2,
]
```

## Actual behavior

```ruby
x = [
  1,
  
    a: 1,
    b: 2,
  ,
]
```
(Note the two commas at the end. The rest of the formatting is **not** what I am reporting)

## RuboCop version

```
$ rubocop -V
1.18.3 (using Parser 3.0.1.1, rubocop-ast 1.7.0, running on ruby 2.7.3 x86_64-linux)
```
